In [1]:
#Whatever codes are written in Python, is available here. The code will be updated here as well as in the Jupyter notebook 
import cmath as cm

z=[4.00+0.001j,4.00-0.001j,-4.00+0.001j,-4.00-0.001j]

def msqrt(x):
    x=cm.sqrt(x)
    if x.imag<=0.0: x*=-1
    return x  

for i in range(len(z)):
    print (z[i],cm.sqrt(z[i]),msqrt(z[i]))

(4+0.001j) (2.0000000156249995+0.00024999999804687506j) (2.0000000156249995+0.00024999999804687506j)
(4-0.001j) (2.0000000156249995-0.00024999999804687506j) (-2.0000000156249995+0.00024999999804687506j)
(-4+0.001j) (0.00024999999804687506+2.0000000156249995j) (0.00024999999804687506+2.0000000156249995j)
(-4-0.001j) (0.00024999999804687506-2.0000000156249995j) (-0.00024999999804687506+2.0000000156249995j)


In [2]:
import cmath as cm
import scipy as sp
from scipy.interpolate import pade 
import numpy as np
from numpy.polynomial import Polynomial as poly

In [3]:
import cmath as cm
import scipy as sp
from scipy.interpolate import pade 
import numpy as np
from numpy.polynomial import Polynomial as poly

#Second assignment: Finding the least square Pade approximant

#Defining the function and noise
def fn(x):
    fn=x/((x+57j)*(x+44j))
    #fn=(x+2j)*(x-2j)
    return fn

def noise(x):
    noise=1+np.random.normal()*x
    return noise

#Getting the data points
x=np.linspace(1,150,150)
fa=[]
for i in range(150):
    fa.append(fn(x[i]))
    fa[i]=fa[i]*noise(0.001)
    #print (x[i])#,fa[i])

#Getting the coefficients
coeff=np.polyfit(x,fa,10)
coeff=np.flip(coeff)

#Using Pade Approximation
n,m=2,1
p,q=pade(coeff,n,m)

print(q)

# Print the evaluated Pade values
#for i in range(len(x)):
    #print("x =", x[i], ", Pade approximation =", p(x[i])/q(x[i]),"Actual value = ",fa[i])

p.r

                        2
(0.001967 + 0.003279j) x + (-0.02713 + -0.05485j) x + 1


array([-0.17197797-0.09801837j])

In [4]:
#q.r

In [5]:
#Making sense of delta
a0=[1.04e-15,0.86e-15,-7.15e-15]
r=[0.96e-15,0.92e-15,-11.9e-15]
md=[1927,1762,1864.85]
mds=[2049,1898,2010.26]

for i in range(3):
    coeff=[0.5*r[i],0,1/a0[i]]
    pcotdelta=np.poly1d(coeff)
    
    ix=[1j,0]
    ix=np.poly1d(ix)
    root=np.roots(pcotdelta-ix)
    conv=140.0/2.7e15
    pbm=root*conv*(1/1j)
    for j in range(len(pbm)):
        if np.absolute(pbm[j].imag)==0:
            pb=pbm[j]
    #print ("*",pb)
    E = ((md[i]**2-pb**2)**0.5)+((mds[i]**2-pb**2)**0.5)
    delta=E-md[i]-mds[i]
    print (delta)

    #[-0.+1.41534629e+15j  0.-1.41534629e+15j]


(-10.619752645662174+0j)
(-13.379736648406833+0j)
(-0.09312218238051173+0j)


In [6]:
def func(a0, r, p):
    pcosdelta = (1.0 / a0) + (0.5 * r * (p**2))
    return pcosdelta
    #den=(1.0/a0)+(0.5*r*E)-1j*np.sqrt(E)
    #return den

In [7]:
"""
#Pade try 1
# Getting the data points required
num = 10
E = np.linspace(1, num, num)
a0 = 1.04
r = 0.96
pd = [pcosdelta(a0, r, E[i]) for i in range(len(E))]

# Numerator and denominator coefficients
m = 1
n = 2
coeff = [1] * (m + 1 + n + 1)

# Constructing the least squares function
def ls(coeff, num, E, pd, m, n):
    def g(E):
        num_val = sum(coeff[j] * E**j for j in range(m + 1))
        den_val = 1 + sum(coeff[m + 1 + j] * E**(j + 1) for j in range(n))
        return num_val / den_val

    lsval = sum((pd[i] - g(E[i]))**2 for i in range(num))
    return lsval

# Minimize the least squares function
result = sp.optimize.minimize(ls, coeff, args=(num, E, pd, m, n))

# Output the result
print("Optimized coefficients:", result.x)
"""

'\n#Pade try 1\n# Getting the data points required\nnum = 10\nE = np.linspace(1, num, num)\na0 = 1.04\nr = 0.96\npd = [pcosdelta(a0, r, E[i]) for i in range(len(E))]\n\n# Numerator and denominator coefficients\nm = 1\nn = 2\ncoeff = [1] * (m + 1 + n + 1)\n\n# Constructing the least squares function\ndef ls(coeff, num, E, pd, m, n):\n    def g(E):\n        num_val = sum(coeff[j] * E**j for j in range(m + 1))\n        den_val = 1 + sum(coeff[m + 1 + j] * E**(j + 1) for j in range(n))\n        return num_val / den_val\n\n    lsval = sum((pd[i] - g(E[i]))**2 for i in range(num))\n    return lsval\n\n# Minimize the least squares function\nresult = sp.optimize.minimize(ls, coeff, args=(num, E, pd, m, n))\n\n# Output the result\nprint("Optimized coefficients:", result.x)\n'

In [8]:
#Making sense of delta
a0=[1.04,0.86,-7.15]
r=[0.96,0.92,-11.9]
md=[1927,1762,1864.85]
mds=[2049,1898,2010.26]

for i in range(3):
    coeff=[0.5*r[i],0,1/a0[i]]
    pcotdelta=np.poly1d(coeff)
    ix=[1j,0]
    ix=np.poly1d(ix)
    root=np.roots(pcotdelta-ix)
    conv=197.327
    pbm=np.imag(root*conv)#*(1/1j)
    for j in range(len(pbm)):
        if np.absolute(pbm[j].imag)==0:
            pb=pbm[j]
    #print ("*",pb)
    E = ((md[i]**2-pb**2)**0.5)+((mds[i]**2-pb**2)**0.5)
    delta=E-md[i]-mds[i]
    print (delta)

-10.054432137712865
-15.029201637892584
-0.16593301876469013


In [13]:
#Constructing Pade Approximant using polynomial fit (Without noise)
#Hypothesis: This method might give a lot of errors

# Getting the data points required
#t=p**2
num = 100
p = np.linspace(1, num, num)
a0 = 1.04
r = 0.96
pd = [func(a0, r, p[i]) for i in range(len(p))]
#print(t,pd)

#Constructing the Pade polynomial fitting the data

# 1. Finding the best order polynomial for the function

ks=[]
for i in range(11):
    coeff=np.polyfit(p,pd,i)
    poly=np.poly1d(coeff)
    kaisq=0
    for j in range(num):
        kaisq=kaisq+(pd[j]-poly(p[j]))**2
    ks.append(kaisq)
imin=np.argmin(ks)
coeff=np.polyfit(p,pd,imin)

# 2. Getting the coefficients
coeff=np.flip(coeff)
print(coeff)

# 3.Optimization of (m,n) in Pade using Kai square
ks=[]
for i in range(len(coeff)-1,-1,-1):
    j=len(coeff)-i-1
    pi,qi=pade(coeff,j,i)
    gi=pi/qi
    kaisq=0
    for j in range(num):
        kaisq=kaisq+(pd[j]-pi(x[j])/qi(x[j]))**2
    ks.append(kaisq)
i=np.argmin(ks)
p=0
q=0
p,q=pade(coeff,i,len(coeff)-1-i)
p.r

[ 9.61538462e-01 -1.83963679e-14  4.80000000e-01]


array([1.91628832e-14+1.41534629j, 1.91628832e-14-1.41534629j])